plugin 'cocoapods-user-defined-build-types'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/sybrin-innovations/Sybrin.iOS.Pods.git'

enable_user_defined_build_types!

platform :ios, '12.4'

target 'nativeexample' do
  
  use_unimodules!
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])

  #Pods for iOS native implementation
  pod "Sybrin.iOS.Identity", :build_type => :dynamic_framework

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
end